GET http://localhost:3000/locations

###






GET http://localhost:3000/locations

###

POST http://localhost:3000/locations
Content-Type: application/json

{
    "sightingType": "Person",
    "sightingCoordinates": "Name",
    "sightingUser": "User"
}

###

PATCH http://localhost:3000/locations/65ce756af191151166ade27d
Content-Type: application/json

{
    "sightingType": "CryptidTest",
    "sightingCoordinatesX": "37.61",
    "sightingCoordinatesY": "-122.011",
    "sightingUser": "User"
}


###

DELETE http://localhost:3000/locations/65ce756af191151166ade27d
