GET http://localhost:3000/locations

###






GET http://localhost:3000/locations

###

POST http://localhost:3000/locations
Content-Type: application/json

{
    "sightingType": "Person",
    "sightingCoordinates": "Name",
    "sightingUser": "User"
}

###

PATCH http://localhost:3000/locations/65cbd7540f281a9de580382e
Content-Type: application/json

{
    "sightingType": "Person",
    "sightingCoordinates": "Name",
    "sightingUser": "User"
}


###

DELETE http://localhost:3000/locations/65cbd7540f281a9de580382e
